### ISSUE TITLE
Knell's Flat Crit Damage Bonus Should be +1.5x; Currently it's +2.5x

### ISSUE THREAD

**Issue by ProfHugo** [pa001024/riven-mirror#12]
Describe the bug:
The bonus crit damage portion of Death Knell is +0.5x per stack (up to 3 stacks, or +1.5x). Right now it's +2.5x.

To Reproduce
Go to the tab for Knell.

**Comment by pa001024** [comment]
I'm not sure. Previous tests showed the bonus is 2.5x.

I'll test again.

**Comment by ProfHugo** [comment]
Interesting. I'll do some ingame testings on my end to see if it's actually +2.5x. If so then it's definitely a typo made by DE (lol) and definitely should be made more well known by the community.

**Comment by pa001024** [comment]
Test target: Corrupted Ancient
MOD: no damage mods
Knell:
headshot&nocrit = 306
headshot&crit 917/1223/1528/1834 with Death Knell 0/1/2/3 stack

So it's 1.5x / 2x / 2.5x / 3x final Crit Multiplier.

Equals to +0x / 0.5x / 1x / 1.5x bonus.

Ok, I believe it has been changed since the update.

Now, fixed by b6242fd898a71513aee54284d2370f4902ef17a1
